#!/bin/bash
source lib/lib.sh
echo " +-----------------------------+"
echo " |          Graphium           |"
echo " | © Universidad Simon Bolivar |"
echo " +-----------------------------+"
echo -n " Creating graph DB..."
java $FLAGS -classpath $LIBS ve.usb.ldc.graphium.load.LoadGraph $@ 2>> log/Graphium.log
echo " Done."
