#!/bin/bash
source lib/lib.sh
echo " +-----------------------------+"
echo " |          Graphium           |"
echo " | © Universidad Simon Bolivar |"
echo " +-----------------------------+"
echo -n " Creating graph DB..."
mkdir -p log
java $FLAGS -classpath $LIBS ve.usb.ldc.graphium.load.LoadGraph $@ 2>> log/Graphium.log
if [ $? -ne 0 ]; then
	echo ""
	echo " Something went wrong... Check log/Graphium.log"
	exit 1
fi
echo " Done."
